### PR TITLE
Split Fund name string to further fields

### PR DESCRIPTION
**Pull request by rtshiva**
Fund Name field was containing ISIN, Advisor & Registrar in the earlier commit. This patch has modified the output to show Fund Name separate from ISIN, Advisor & Registrar in their own columns. 

Also fixed the regex parsing to ensure that whenever fund name goes to next line it is also considered and included in the final output generated.

### CODE REVIEW

**Comment by SudheerNotes** [comment]
I'll review and and update.

**Comment by rtshiva** [comment]
@SudheerNotes , one more change was needed on top of this hence i had closed this PR. you can look at the latest changes in https://github.com/SudheerNotes/cams2csv/compare/main...rtshiva:cams2csv:main

**Comment by SudheerNotes** [comment]
Ah ok...I'll have a look at it this weekend.

**Comment by rtshiva** [comment]
here is the new PR with the fixes https://github.com/SudheerNotes/cams2csv/pull/9/files . you can merge if the changes look good.

**Pull request closed without merging**
